language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
    sudo aptitude install libevent && pip install -r REQUIREMENTS --use-mirrors
# command to run tests
script: make ci_test

